import Head from "next/head";
import { useAuth } from "../lib/auth";
import Typed from "typed.js";
import { useEffect, useRef } from "react";

export default function Home() {
  const typedElement = useRef(null);

  useEffect(() => {
    const typed = new Typed(typedElement.current, {
      strings: ["tasks.", "subjects.", "life."],
      typeSpeed: 100,
      backSpeed: 120,
      loop: true,
    });

    return () => {
      typed.destroy();
    };
  }, []);

  const auth = useAuth();

  return (
    <>
      <Head>
        <title>Home - Study Tasks</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {auth.user && (
        <>
          <div className="min-h-full">
            <div className="flex flex-col items-center justify-center text-center px-6 py-8 mx-auto lg:py-0 min-h-full">
              <h1 className="mb-4 text-4xl font-bold leading-none text-nord6 md:text-5xl lg:text-6xl">
                Welcome to Study Tasks!
              </h1>
              <div className="flex">
                <p className="mb-6 text-lg font-normal text-indigo-200 lg:text-2xl mr-2">
                  Use the menu to manage your academic
                </p>
                <p className="text-lg font-normal text-indigo-200 lg:text-2xl">
                  <span ref={typedElement} />
                </p>
              </div>
            </div>
          </div>
        </>
      )}
    </>
  );
}
